
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const EDIT_BLOG_SUCCESS = 'EDIT_BLOG_SUCCESS';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const LIKE_BLOG_SUCCESS = 'LIKE_BLOG_SUCCESS';
export const COMMENT_BLOG_SUCCESS = 'COMMENT_BLOG_SUCCESS';
export const SEARCH_BLOGS_SUCCESS = 'SEARCH_BLOGS_SUCCESS';
export const FILTER_BLOGS_SUCCESS = 'FILTER_BLOGS_SUCCESS';
export const SORT_BLOGS_SUCCESS = 'SORT_BLOGS_SUCCESS';